// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using BoomTax.Api.SampleProject;
using Microsoft.Rest;

namespace BoomTax.Api.SampleProject
{
    public partial class BoomTaxApi : ServiceClient<BoomTaxApi>, IBoomTaxApi
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IEfileRequestOperations _efileRequest;
        
        public virtual IEfileRequestOperations EfileRequest
        {
            get { return this._efileRequest; }
        }
        
        private IEfileResponseOperations _efileResponse;
        
        public virtual IEfileResponseOperations EfileResponse
        {
            get { return this._efileResponse; }
        }
        
        private IFilingOperations _filing;
        
        public virtual IFilingOperations Filing
        {
            get { return this._filing; }
        }
        
        private IFilingTypeOperations _filingType;
        
        public virtual IFilingTypeOperations FilingType
        {
            get { return this._filingType; }
        }
        
        private IForm1094COperations _form1094C;
        
        public virtual IForm1094COperations Form1094C
        {
            get { return this._form1094C; }
        }
        
        private IForm1095COperations _form1095C;
        
        public virtual IForm1095COperations Form1095C
        {
            get { return this._form1095C; }
        }
        
        /// <summary>
        /// Initializes a new instance of the BoomTaxApi class.
        /// </summary>
        public BoomTaxApi()
            : base()
        {
            this._efileRequest = new EfileRequestOperations(this);
            this._efileResponse = new EfileResponseOperations(this);
            this._filing = new FilingOperations(this);
            this._filingType = new FilingTypeOperations(this);
            this._form1094C = new Form1094COperations(this);
            this._form1095C = new Form1095COperations(this);
            this._baseUri = new Uri("http://api.boomtax.com");
        }
        
        /// <summary>
        /// Initializes a new instance of the BoomTaxApi class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public BoomTaxApi(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._efileRequest = new EfileRequestOperations(this);
            this._efileResponse = new EfileResponseOperations(this);
            this._filing = new FilingOperations(this);
            this._filingType = new FilingTypeOperations(this);
            this._form1094C = new Form1094COperations(this);
            this._form1095C = new Form1095COperations(this);
            this._baseUri = new Uri("http://api.boomtax.com");
        }
        
        /// <summary>
        /// Initializes a new instance of the BoomTaxApi class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public BoomTaxApi(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._efileRequest = new EfileRequestOperations(this);
            this._efileResponse = new EfileResponseOperations(this);
            this._filing = new FilingOperations(this);
            this._filingType = new FilingTypeOperations(this);
            this._form1094C = new Form1094COperations(this);
            this._form1095C = new Form1095COperations(this);
            this._baseUri = new Uri("http://api.boomtax.com");
        }
        
        /// <summary>
        /// Initializes a new instance of the BoomTaxApi class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public BoomTaxApi(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the BoomTaxApi class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public BoomTaxApi(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the BoomTaxApi class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public BoomTaxApi(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
