// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using BoomTax.Api.SampleProject;
using BoomTax.Api.SampleProject.Models;
using Microsoft.Rest;

namespace BoomTax.Api.SampleProject
{
    public static partial class EfileRequestOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IEfileRequestOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static EfileRequest GetEfileRequest(this IEfileRequestOperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IEfileRequestOperations)s).GetEfileRequestAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IEfileRequestOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<EfileRequest> GetEfileRequestAsync(this IEfileRequestOperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<BoomTax.Api.SampleProject.Models.EfileRequest> result = await operations.GetEfileRequestWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IEfileRequestOperations.
        /// </param>
        /// <param name='filingId'>
        /// Required.
        /// </param>
        public static IList<EfileRequest> GetEfileRequests(this IEfileRequestOperations operations, int filingId)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IEfileRequestOperations)s).GetEfileRequestsAsync(filingId);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IEfileRequestOperations.
        /// </param>
        /// <param name='filingId'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<EfileRequest>> GetEfileRequestsAsync(this IEfileRequestOperations operations, int filingId, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<BoomTax.Api.SampleProject.Models.EfileRequest>> result = await operations.GetEfileRequestsWithOperationResponseAsync(filingId, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IEfileRequestOperations.
        /// </param>
        /// <param name='filingId'>
        /// Required.
        /// </param>
        /// <param name='emails'>
        /// Required.
        /// </param>
        /// <param name='isSilent'>
        /// Required.
        /// </param>
        public static IList<int> Post(this IEfileRequestOperations operations, int filingId, string emails, bool isSilent)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IEfileRequestOperations)s).PostAsync(filingId, emails, isSilent);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IEfileRequestOperations.
        /// </param>
        /// <param name='filingId'>
        /// Required.
        /// </param>
        /// <param name='emails'>
        /// Required.
        /// </param>
        /// <param name='isSilent'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<int>> PostAsync(this IEfileRequestOperations operations, int filingId, string emails, bool isSilent, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<int>> result = await operations.PostWithOperationResponseAsync(filingId, emails, isSilent, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
