// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using BoomTax.Api.SampleProject;
using BoomTax.Api.SampleProject.Models;
using Microsoft.Rest;

namespace BoomTax.Api.SampleProject
{
    public static partial class EfileResponseOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IEfileResponseOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static EfileResponse Get(this IEfileResponseOperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IEfileResponseOperations)s).GetAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IEfileResponseOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<EfileResponse> GetAsync(this IEfileResponseOperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<BoomTax.Api.SampleProject.Models.EfileResponse> result = await operations.GetWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
