// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using BoomTax.Api.SampleProject;
using BoomTax.Api.SampleProject.Models;
using Microsoft.Rest;

namespace BoomTax.Api.SampleProject
{
    public static partial class Form1095COperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IForm1095COperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static string Delete(this IForm1095COperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IForm1095COperations)s).DeleteAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IForm1095COperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<string> DeleteAsync(this IForm1095COperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<string> result = await operations.DeleteWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IForm1095COperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static Form1095C Get(this IForm1095COperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IForm1095COperations)s).GetAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IForm1095COperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Form1095C> GetAsync(this IForm1095COperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<BoomTax.Api.SampleProject.Models.Form1095C> result = await operations.GetWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IForm1095COperations.
        /// </param>
        /// <param name='filingId'>
        /// Required.
        /// </param>
        /// <param name='form1095C'>
        /// Required.
        /// </param>
        public static int Post(this IForm1095COperations operations, int filingId, Form1095C form1095C)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IForm1095COperations)s).PostAsync(filingId, form1095C);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IForm1095COperations.
        /// </param>
        /// <param name='filingId'>
        /// Required.
        /// </param>
        /// <param name='form1095C'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<int> PostAsync(this IForm1095COperations operations, int filingId, Form1095C form1095C, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<int> result = await operations.PostWithOperationResponseAsync(filingId, form1095C, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IForm1095COperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='form1095C'>
        /// Required.
        /// </param>
        public static Form1095C Put(this IForm1095COperations operations, int id, Form1095C form1095C)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IForm1095COperations)s).PutAsync(id, form1095C);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the BoomTax.Api.SampleProject.IForm1095COperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='form1095C'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Form1095C> PutAsync(this IForm1095COperations operations, int id, Form1095C form1095C, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<BoomTax.Api.SampleProject.Models.Form1095C> result = await operations.PutWithOperationResponseAsync(id, form1095C, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
