// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using BoomTax.Api.SampleProject;
using Microsoft.Rest;

namespace BoomTax.Api.SampleProject
{
    public partial interface IBoomTaxApi : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri
        {
            get; set; 
        }
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        ServiceClientCredentials Credentials
        {
            get; set; 
        }
        
        IEfileRequestOperations EfileRequest
        {
            get; 
        }
        
        IEfileResponseOperations EfileResponse
        {
            get; 
        }
        
        IFilingOperations Filing
        {
            get; 
        }
        
        IFilingTypeOperations FilingType
        {
            get; 
        }
        
        IForm1094COperations Form1094C
        {
            get; 
        }
        
        IForm1095COperations Form1095C
        {
            get; 
        }
    }
}
