// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using BoomTax.Api.SampleProject.Models;
using Microsoft.Rest;

namespace BoomTax.Api.SampleProject
{
    public partial interface IEfileRequestOperations
    {
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<EfileRequest>> GetEfileRequestWithOperationResponseAsync(int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filingId'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<EfileRequest>>> GetEfileRequestsWithOperationResponseAsync(int filingId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filingId'>
        /// Required.
        /// </param>
        /// <param name='emails'>
        /// Required.
        /// </param>
        /// <param name='isSilent'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<int>>> PostWithOperationResponseAsync(int filingId, string emails, bool isSilent, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
