// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace BoomTax.Api.SampleProject.Models
{
    public partial class CoveredIndividual
    {
        private bool? _all12Months;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? All12Months
        {
            get { return this._all12Months; }
            set { this._all12Months = value; }
        }
        
        private bool? _apr;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Apr
        {
            get { return this._apr; }
            set { this._apr = value; }
        }
        
        private bool? _aug;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Aug
        {
            get { return this._aug; }
            set { this._aug = value; }
        }
        
        private bool? _dec;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Dec
        {
            get { return this._dec; }
            set { this._dec = value; }
        }
        
        private DateTimeOffset? _dob;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? Dob
        {
            get { return this._dob; }
            set { this._dob = value; }
        }
        
        private bool? _feb;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Feb
        {
            get { return this._feb; }
            set { this._feb = value; }
        }
        
        private string _firstName;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string FirstName
        {
            get { return this._firstName; }
            set { this._firstName = value; }
        }
        
        private bool? _jan;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Jan
        {
            get { return this._jan; }
            set { this._jan = value; }
        }
        
        private bool? _jul;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Jul
        {
            get { return this._jul; }
            set { this._jul = value; }
        }
        
        private bool? _jun;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Jun
        {
            get { return this._jun; }
            set { this._jun = value; }
        }
        
        private string _lastName;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string LastName
        {
            get { return this._lastName; }
            set { this._lastName = value; }
        }
        
        private bool? _mar;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Mar
        {
            get { return this._mar; }
            set { this._mar = value; }
        }
        
        private bool? _may;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? May
        {
            get { return this._may; }
            set { this._may = value; }
        }
        
        private string _middleName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string MiddleName
        {
            get { return this._middleName; }
            set { this._middleName = value; }
        }
        
        private bool? _nov;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Nov
        {
            get { return this._nov; }
            set { this._nov = value; }
        }
        
        private bool? _oct;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Oct
        {
            get { return this._oct; }
            set { this._oct = value; }
        }
        
        private bool? _sep;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Sep
        {
            get { return this._sep; }
            set { this._sep = value; }
        }
        
        private string _ssn;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Ssn
        {
            get { return this._ssn; }
            set { this._ssn = value; }
        }
        
        private string _suffix;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Suffix
        {
            get { return this._suffix; }
            set { this._suffix = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the CoveredIndividual class.
        /// </summary>
        public CoveredIndividual()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the CoveredIndividual class with
        /// required arguments.
        /// </summary>
        public CoveredIndividual(string firstName, string lastName)
            : this()
        {
            if (firstName == null)
            {
                throw new ArgumentNullException("firstName");
            }
            if (lastName == null)
            {
                throw new ArgumentNullException("lastName");
            }
            this.FirstName = firstName;
            this.LastName = lastName;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken all12MonthsValue = inputObject["All12Months"];
                if (all12MonthsValue != null && all12MonthsValue.Type != JTokenType.Null)
                {
                    this.All12Months = ((bool)all12MonthsValue);
                }
                JToken aprValue = inputObject["Apr"];
                if (aprValue != null && aprValue.Type != JTokenType.Null)
                {
                    this.Apr = ((bool)aprValue);
                }
                JToken augValue = inputObject["Aug"];
                if (augValue != null && augValue.Type != JTokenType.Null)
                {
                    this.Aug = ((bool)augValue);
                }
                JToken decValue = inputObject["Dec"];
                if (decValue != null && decValue.Type != JTokenType.Null)
                {
                    this.Dec = ((bool)decValue);
                }
                JToken dobValue = inputObject["Dob"];
                if (dobValue != null && dobValue.Type != JTokenType.Null)
                {
                    this.Dob = ((DateTimeOffset)dobValue);
                }
                JToken febValue = inputObject["Feb"];
                if (febValue != null && febValue.Type != JTokenType.Null)
                {
                    this.Feb = ((bool)febValue);
                }
                JToken firstNameValue = inputObject["FirstName"];
                if (firstNameValue != null && firstNameValue.Type != JTokenType.Null)
                {
                    this.FirstName = ((string)firstNameValue);
                }
                JToken janValue = inputObject["Jan"];
                if (janValue != null && janValue.Type != JTokenType.Null)
                {
                    this.Jan = ((bool)janValue);
                }
                JToken julValue = inputObject["Jul"];
                if (julValue != null && julValue.Type != JTokenType.Null)
                {
                    this.Jul = ((bool)julValue);
                }
                JToken junValue = inputObject["Jun"];
                if (junValue != null && junValue.Type != JTokenType.Null)
                {
                    this.Jun = ((bool)junValue);
                }
                JToken lastNameValue = inputObject["LastName"];
                if (lastNameValue != null && lastNameValue.Type != JTokenType.Null)
                {
                    this.LastName = ((string)lastNameValue);
                }
                JToken marValue = inputObject["Mar"];
                if (marValue != null && marValue.Type != JTokenType.Null)
                {
                    this.Mar = ((bool)marValue);
                }
                JToken mayValue = inputObject["May"];
                if (mayValue != null && mayValue.Type != JTokenType.Null)
                {
                    this.May = ((bool)mayValue);
                }
                JToken middleNameValue = inputObject["MiddleName"];
                if (middleNameValue != null && middleNameValue.Type != JTokenType.Null)
                {
                    this.MiddleName = ((string)middleNameValue);
                }
                JToken novValue = inputObject["Nov"];
                if (novValue != null && novValue.Type != JTokenType.Null)
                {
                    this.Nov = ((bool)novValue);
                }
                JToken octValue = inputObject["Oct"];
                if (octValue != null && octValue.Type != JTokenType.Null)
                {
                    this.Oct = ((bool)octValue);
                }
                JToken sepValue = inputObject["Sep"];
                if (sepValue != null && sepValue.Type != JTokenType.Null)
                {
                    this.Sep = ((bool)sepValue);
                }
                JToken ssnValue = inputObject["Ssn"];
                if (ssnValue != null && ssnValue.Type != JTokenType.Null)
                {
                    this.Ssn = ((string)ssnValue);
                }
                JToken suffixValue = inputObject["Suffix"];
                if (suffixValue != null && suffixValue.Type != JTokenType.Null)
                {
                    this.Suffix = ((string)suffixValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type CoveredIndividual
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.FirstName == null)
            {
                throw new ArgumentNullException("FirstName");
            }
            if (this.LastName == null)
            {
                throw new ArgumentNullException("LastName");
            }
            if (this.All12Months != null)
            {
                outputObject["All12Months"] = this.All12Months.Value;
            }
            if (this.Apr != null)
            {
                outputObject["Apr"] = this.Apr.Value;
            }
            if (this.Aug != null)
            {
                outputObject["Aug"] = this.Aug.Value;
            }
            if (this.Dec != null)
            {
                outputObject["Dec"] = this.Dec.Value;
            }
            if (this.Dob != null)
            {
                outputObject["Dob"] = this.Dob.Value;
            }
            if (this.Feb != null)
            {
                outputObject["Feb"] = this.Feb.Value;
            }
            if (this.FirstName != null)
            {
                outputObject["FirstName"] = this.FirstName;
            }
            if (this.Jan != null)
            {
                outputObject["Jan"] = this.Jan.Value;
            }
            if (this.Jul != null)
            {
                outputObject["Jul"] = this.Jul.Value;
            }
            if (this.Jun != null)
            {
                outputObject["Jun"] = this.Jun.Value;
            }
            if (this.LastName != null)
            {
                outputObject["LastName"] = this.LastName;
            }
            if (this.Mar != null)
            {
                outputObject["Mar"] = this.Mar.Value;
            }
            if (this.May != null)
            {
                outputObject["May"] = this.May.Value;
            }
            if (this.MiddleName != null)
            {
                outputObject["MiddleName"] = this.MiddleName;
            }
            if (this.Nov != null)
            {
                outputObject["Nov"] = this.Nov.Value;
            }
            if (this.Oct != null)
            {
                outputObject["Oct"] = this.Oct.Value;
            }
            if (this.Sep != null)
            {
                outputObject["Sep"] = this.Sep.Value;
            }
            if (this.Ssn != null)
            {
                outputObject["Ssn"] = this.Ssn;
            }
            if (this.Suffix != null)
            {
                outputObject["Suffix"] = this.Suffix;
            }
            return outputObject;
        }
    }
}
