// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace BoomTax.Api.SampleProject.Models
{
    public partial class EfileRequest
    {
        private DateTimeOffset? _dateCompleted;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? DateCompleted
        {
            get { return this._dateCompleted; }
            set { this._dateCompleted = value; }
        }
        
        private DateTimeOffset? _dateStarted;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? DateStarted
        {
            get { return this._dateStarted; }
            set { this._dateStarted = value; }
        }
        
        private int? _efileResponseId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? EfileResponseId
        {
            get { return this._efileResponseId; }
            set { this._efileResponseId = value; }
        }
        
        private int? _formGroupId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? FormGroupId
        {
            get { return this._formGroupId; }
            set { this._formGroupId = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private bool? _isComplete;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsComplete
        {
            get { return this._isComplete; }
            set { this._isComplete = value; }
        }
        
        private string _notificationEmails;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string NotificationEmails
        {
            get { return this._notificationEmails; }
            set { this._notificationEmails = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the EfileRequest class.
        /// </summary>
        public EfileRequest()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken dateCompletedValue = inputObject["DateCompleted"];
                if (dateCompletedValue != null && dateCompletedValue.Type != JTokenType.Null)
                {
                    this.DateCompleted = ((DateTimeOffset)dateCompletedValue);
                }
                JToken dateStartedValue = inputObject["DateStarted"];
                if (dateStartedValue != null && dateStartedValue.Type != JTokenType.Null)
                {
                    this.DateStarted = ((DateTimeOffset)dateStartedValue);
                }
                JToken efileResponseIdValue = inputObject["EfileResponseId"];
                if (efileResponseIdValue != null && efileResponseIdValue.Type != JTokenType.Null)
                {
                    this.EfileResponseId = ((int)efileResponseIdValue);
                }
                JToken formGroupIdValue = inputObject["FormGroupId"];
                if (formGroupIdValue != null && formGroupIdValue.Type != JTokenType.Null)
                {
                    this.FormGroupId = ((int)formGroupIdValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken isCompleteValue = inputObject["IsComplete"];
                if (isCompleteValue != null && isCompleteValue.Type != JTokenType.Null)
                {
                    this.IsComplete = ((bool)isCompleteValue);
                }
                JToken notificationEmailsValue = inputObject["NotificationEmails"];
                if (notificationEmailsValue != null && notificationEmailsValue.Type != JTokenType.Null)
                {
                    this.NotificationEmails = ((string)notificationEmailsValue);
                }
            }
        }
    }
}
