// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using BoomTax.Api.SampleProject.Models;
using Newtonsoft.Json.Linq;

namespace BoomTax.Api.SampleProject.Models
{
    public static partial class EfileRequestCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<EfileRequest> DeserializeJson(JToken inputObject)
        {
            IList<EfileRequest> deserializedObject = new List<EfileRequest>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                EfileRequest efileRequest = new EfileRequest();
                efileRequest.DeserializeJson(iListValue);
                deserializedObject.Add(efileRequest);
            }
            return deserializedObject;
        }
    }
}
