// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using BoomTax.Api.SampleProject.Models;
using Newtonsoft.Json.Linq;

namespace BoomTax.Api.SampleProject.Models
{
    public static partial class FilingCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Filing> DeserializeJson(JToken inputObject)
        {
            IList<Filing> deserializedObject = new List<Filing>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Filing filing = new Filing();
                filing.DeserializeJson(iListValue);
                deserializedObject.Add(filing);
            }
            return deserializedObject;
        }
    }
}
