// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using BoomTax.Api.SampleProject.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace BoomTax.Api.SampleProject.Models
{
    public partial class Form1095C
    {
        private string _address;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Address
        {
            get { return this._address; }
            set { this._address = value; }
        }
        
        private string _address2;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Address2
        {
            get { return this._address2; }
            set { this._address2 = value; }
        }
        
        private string _applicableSection4980HAll12Months;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HAll12Months
        {
            get { return this._applicableSection4980HAll12Months; }
            set { this._applicableSection4980HAll12Months = value; }
        }
        
        private string _applicableSection4980HApr;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HApr
        {
            get { return this._applicableSection4980HApr; }
            set { this._applicableSection4980HApr = value; }
        }
        
        private string _applicableSection4980HAug;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HAug
        {
            get { return this._applicableSection4980HAug; }
            set { this._applicableSection4980HAug = value; }
        }
        
        private string _applicableSection4980HDec;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HDec
        {
            get { return this._applicableSection4980HDec; }
            set { this._applicableSection4980HDec = value; }
        }
        
        private string _applicableSection4980HFeb;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HFeb
        {
            get { return this._applicableSection4980HFeb; }
            set { this._applicableSection4980HFeb = value; }
        }
        
        private string _applicableSection4980HJan;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HJan
        {
            get { return this._applicableSection4980HJan; }
            set { this._applicableSection4980HJan = value; }
        }
        
        private string _applicableSection4980HJul;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HJul
        {
            get { return this._applicableSection4980HJul; }
            set { this._applicableSection4980HJul = value; }
        }
        
        private string _applicableSection4980HJun;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HJun
        {
            get { return this._applicableSection4980HJun; }
            set { this._applicableSection4980HJun = value; }
        }
        
        private string _applicableSection4980HMar;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HMar
        {
            get { return this._applicableSection4980HMar; }
            set { this._applicableSection4980HMar = value; }
        }
        
        private string _applicableSection4980HMay;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HMay
        {
            get { return this._applicableSection4980HMay; }
            set { this._applicableSection4980HMay = value; }
        }
        
        private string _applicableSection4980HNov;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HNov
        {
            get { return this._applicableSection4980HNov; }
            set { this._applicableSection4980HNov = value; }
        }
        
        private string _applicableSection4980HOct;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HOct
        {
            get { return this._applicableSection4980HOct; }
            set { this._applicableSection4980HOct = value; }
        }
        
        private string _applicableSection4980HSep;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ApplicableSection4980HSep
        {
            get { return this._applicableSection4980HSep; }
            set { this._applicableSection4980HSep = value; }
        }
        
        private string _city;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string City
        {
            get { return this._city; }
            set { this._city = value; }
        }
        
        private string _countryCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string CountryCode
        {
            get { return this._countryCode; }
            set { this._countryCode = value; }
        }
        
        private IList<CoveredIndividual> _coveredIndividuals;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<CoveredIndividual> CoveredIndividuals
        {
            get { return this._coveredIndividuals; }
            set { this._coveredIndividuals = value; }
        }
        
        private DateTimeOffset? _dateEdited;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? DateEdited
        {
            get { return this._dateEdited; }
            set { this._dateEdited = value; }
        }
        
        private double? _employeeShareAll12Months;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareAll12Months
        {
            get { return this._employeeShareAll12Months; }
            set { this._employeeShareAll12Months = value; }
        }
        
        private double? _employeeShareApr;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareApr
        {
            get { return this._employeeShareApr; }
            set { this._employeeShareApr = value; }
        }
        
        private double? _employeeShareAug;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareAug
        {
            get { return this._employeeShareAug; }
            set { this._employeeShareAug = value; }
        }
        
        private double? _employeeShareDec;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareDec
        {
            get { return this._employeeShareDec; }
            set { this._employeeShareDec = value; }
        }
        
        private double? _employeeShareFeb;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareFeb
        {
            get { return this._employeeShareFeb; }
            set { this._employeeShareFeb = value; }
        }
        
        private double? _employeeShareJan;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareJan
        {
            get { return this._employeeShareJan; }
            set { this._employeeShareJan = value; }
        }
        
        private double? _employeeShareJul;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareJul
        {
            get { return this._employeeShareJul; }
            set { this._employeeShareJul = value; }
        }
        
        private double? _employeeShareJun;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareJun
        {
            get { return this._employeeShareJun; }
            set { this._employeeShareJun = value; }
        }
        
        private double? _employeeShareMar;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareMar
        {
            get { return this._employeeShareMar; }
            set { this._employeeShareMar = value; }
        }
        
        private double? _employeeShareMay;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareMay
        {
            get { return this._employeeShareMay; }
            set { this._employeeShareMay = value; }
        }
        
        private double? _employeeShareNov;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareNov
        {
            get { return this._employeeShareNov; }
            set { this._employeeShareNov = value; }
        }
        
        private double? _employeeShareOct;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareOct
        {
            get { return this._employeeShareOct; }
            set { this._employeeShareOct = value; }
        }
        
        private double? _employeeShareSep;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? EmployeeShareSep
        {
            get { return this._employeeShareSep; }
            set { this._employeeShareSep = value; }
        }
        
        private string _employerPhone;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string EmployerPhone
        {
            get { return this._employerPhone; }
            set { this._employerPhone = value; }
        }
        
        private int? _filingId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? FilingId
        {
            get { return this._filingId; }
            set { this._filingId = value; }
        }
        
        private string _firstName;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string FirstName
        {
            get { return this._firstName; }
            set { this._firstName = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private bool? _isCorrected;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsCorrected
        {
            get { return this._isCorrected; }
            set { this._isCorrected = value; }
        }
        
        private bool? _isSelfInsured;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsSelfInsured
        {
            get { return this._isSelfInsured; }
            set { this._isSelfInsured = value; }
        }
        
        private string _lastName;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string LastName
        {
            get { return this._lastName; }
            set { this._lastName = value; }
        }
        
        private string _middleName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string MiddleName
        {
            get { return this._middleName; }
            set { this._middleName = value; }
        }
        
        private int? _numberOfCoveredIndividuals;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? NumberOfCoveredIndividuals
        {
            get { return this._numberOfCoveredIndividuals; }
            set { this._numberOfCoveredIndividuals = value; }
        }
        
        private string _offerOfCoverageAll12Months;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageAll12Months
        {
            get { return this._offerOfCoverageAll12Months; }
            set { this._offerOfCoverageAll12Months = value; }
        }
        
        private string _offerOfCoverageApr;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageApr
        {
            get { return this._offerOfCoverageApr; }
            set { this._offerOfCoverageApr = value; }
        }
        
        private string _offerOfCoverageAug;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageAug
        {
            get { return this._offerOfCoverageAug; }
            set { this._offerOfCoverageAug = value; }
        }
        
        private string _offerOfCoverageDec;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageDec
        {
            get { return this._offerOfCoverageDec; }
            set { this._offerOfCoverageDec = value; }
        }
        
        private string _offerOfCoverageFeb;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageFeb
        {
            get { return this._offerOfCoverageFeb; }
            set { this._offerOfCoverageFeb = value; }
        }
        
        private string _offerOfCoverageJan;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageJan
        {
            get { return this._offerOfCoverageJan; }
            set { this._offerOfCoverageJan = value; }
        }
        
        private string _offerOfCoverageJul;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageJul
        {
            get { return this._offerOfCoverageJul; }
            set { this._offerOfCoverageJul = value; }
        }
        
        private string _offerOfCoverageJun;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageJun
        {
            get { return this._offerOfCoverageJun; }
            set { this._offerOfCoverageJun = value; }
        }
        
        private string _offerOfCoverageMar;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageMar
        {
            get { return this._offerOfCoverageMar; }
            set { this._offerOfCoverageMar = value; }
        }
        
        private string _offerOfCoverageMay;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageMay
        {
            get { return this._offerOfCoverageMay; }
            set { this._offerOfCoverageMay = value; }
        }
        
        private string _offerOfCoverageNov;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageNov
        {
            get { return this._offerOfCoverageNov; }
            set { this._offerOfCoverageNov = value; }
        }
        
        private string _offerOfCoverageOct;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageOct
        {
            get { return this._offerOfCoverageOct; }
            set { this._offerOfCoverageOct = value; }
        }
        
        private string _offerOfCoverageSep;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OfferOfCoverageSep
        {
            get { return this._offerOfCoverageSep; }
            set { this._offerOfCoverageSep = value; }
        }
        
        private string _planStartMonth;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PlanStartMonth
        {
            get { return this._planStartMonth; }
            set { this._planStartMonth = value; }
        }
        
        private string _ssn;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Ssn
        {
            get { return this._ssn; }
            set { this._ssn = value; }
        }
        
        private string _state;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string State
        {
            get { return this._state; }
            set { this._state = value; }
        }
        
        private string _status;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Status
        {
            get { return this._status; }
            set { this._status = value; }
        }
        
        private string _suffix;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Suffix
        {
            get { return this._suffix; }
            set { this._suffix = value; }
        }
        
        private string _zip;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Zip
        {
            get { return this._zip; }
            set { this._zip = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Form1095C class.
        /// </summary>
        public Form1095C()
        {
            this.CoveredIndividuals = new LazyList<CoveredIndividual>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken addressValue = inputObject["Address"];
                if (addressValue != null && addressValue.Type != JTokenType.Null)
                {
                    this.Address = ((string)addressValue);
                }
                JToken address2Value = inputObject["Address2"];
                if (address2Value != null && address2Value.Type != JTokenType.Null)
                {
                    this.Address2 = ((string)address2Value);
                }
                JToken applicableSection4980HAll12MonthsValue = inputObject["ApplicableSection4980HAll12Months"];
                if (applicableSection4980HAll12MonthsValue != null && applicableSection4980HAll12MonthsValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HAll12Months = ((string)applicableSection4980HAll12MonthsValue);
                }
                JToken applicableSection4980HAprValue = inputObject["ApplicableSection4980HApr"];
                if (applicableSection4980HAprValue != null && applicableSection4980HAprValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HApr = ((string)applicableSection4980HAprValue);
                }
                JToken applicableSection4980HAugValue = inputObject["ApplicableSection4980HAug"];
                if (applicableSection4980HAugValue != null && applicableSection4980HAugValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HAug = ((string)applicableSection4980HAugValue);
                }
                JToken applicableSection4980HDecValue = inputObject["ApplicableSection4980HDec"];
                if (applicableSection4980HDecValue != null && applicableSection4980HDecValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HDec = ((string)applicableSection4980HDecValue);
                }
                JToken applicableSection4980HFebValue = inputObject["ApplicableSection4980HFeb"];
                if (applicableSection4980HFebValue != null && applicableSection4980HFebValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HFeb = ((string)applicableSection4980HFebValue);
                }
                JToken applicableSection4980HJanValue = inputObject["ApplicableSection4980HJan"];
                if (applicableSection4980HJanValue != null && applicableSection4980HJanValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HJan = ((string)applicableSection4980HJanValue);
                }
                JToken applicableSection4980HJulValue = inputObject["ApplicableSection4980HJul"];
                if (applicableSection4980HJulValue != null && applicableSection4980HJulValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HJul = ((string)applicableSection4980HJulValue);
                }
                JToken applicableSection4980HJunValue = inputObject["ApplicableSection4980HJun"];
                if (applicableSection4980HJunValue != null && applicableSection4980HJunValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HJun = ((string)applicableSection4980HJunValue);
                }
                JToken applicableSection4980HMarValue = inputObject["ApplicableSection4980HMar"];
                if (applicableSection4980HMarValue != null && applicableSection4980HMarValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HMar = ((string)applicableSection4980HMarValue);
                }
                JToken applicableSection4980HMayValue = inputObject["ApplicableSection4980HMay"];
                if (applicableSection4980HMayValue != null && applicableSection4980HMayValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HMay = ((string)applicableSection4980HMayValue);
                }
                JToken applicableSection4980HNovValue = inputObject["ApplicableSection4980HNov"];
                if (applicableSection4980HNovValue != null && applicableSection4980HNovValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HNov = ((string)applicableSection4980HNovValue);
                }
                JToken applicableSection4980HOctValue = inputObject["ApplicableSection4980HOct"];
                if (applicableSection4980HOctValue != null && applicableSection4980HOctValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HOct = ((string)applicableSection4980HOctValue);
                }
                JToken applicableSection4980HSepValue = inputObject["ApplicableSection4980HSep"];
                if (applicableSection4980HSepValue != null && applicableSection4980HSepValue.Type != JTokenType.Null)
                {
                    this.ApplicableSection4980HSep = ((string)applicableSection4980HSepValue);
                }
                JToken cityValue = inputObject["City"];
                if (cityValue != null && cityValue.Type != JTokenType.Null)
                {
                    this.City = ((string)cityValue);
                }
                JToken countryCodeValue = inputObject["CountryCode"];
                if (countryCodeValue != null && countryCodeValue.Type != JTokenType.Null)
                {
                    this.CountryCode = ((string)countryCodeValue);
                }
                JToken coveredIndividualsSequence = ((JToken)inputObject["CoveredIndividuals"]);
                if (coveredIndividualsSequence != null && coveredIndividualsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken coveredIndividualsValue in ((JArray)coveredIndividualsSequence))
                    {
                        CoveredIndividual coveredIndividual = new CoveredIndividual();
                        coveredIndividual.DeserializeJson(coveredIndividualsValue);
                        this.CoveredIndividuals.Add(coveredIndividual);
                    }
                }
                JToken dateEditedValue = inputObject["DateEdited"];
                if (dateEditedValue != null && dateEditedValue.Type != JTokenType.Null)
                {
                    this.DateEdited = ((DateTimeOffset)dateEditedValue);
                }
                JToken employeeShareAll12MonthsValue = inputObject["EmployeeShareAll12Months"];
                if (employeeShareAll12MonthsValue != null && employeeShareAll12MonthsValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareAll12Months = ((double)employeeShareAll12MonthsValue);
                }
                JToken employeeShareAprValue = inputObject["EmployeeShareApr"];
                if (employeeShareAprValue != null && employeeShareAprValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareApr = ((double)employeeShareAprValue);
                }
                JToken employeeShareAugValue = inputObject["EmployeeShareAug"];
                if (employeeShareAugValue != null && employeeShareAugValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareAug = ((double)employeeShareAugValue);
                }
                JToken employeeShareDecValue = inputObject["EmployeeShareDec"];
                if (employeeShareDecValue != null && employeeShareDecValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareDec = ((double)employeeShareDecValue);
                }
                JToken employeeShareFebValue = inputObject["EmployeeShareFeb"];
                if (employeeShareFebValue != null && employeeShareFebValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareFeb = ((double)employeeShareFebValue);
                }
                JToken employeeShareJanValue = inputObject["EmployeeShareJan"];
                if (employeeShareJanValue != null && employeeShareJanValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareJan = ((double)employeeShareJanValue);
                }
                JToken employeeShareJulValue = inputObject["EmployeeShareJul"];
                if (employeeShareJulValue != null && employeeShareJulValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareJul = ((double)employeeShareJulValue);
                }
                JToken employeeShareJunValue = inputObject["EmployeeShareJun"];
                if (employeeShareJunValue != null && employeeShareJunValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareJun = ((double)employeeShareJunValue);
                }
                JToken employeeShareMarValue = inputObject["EmployeeShareMar"];
                if (employeeShareMarValue != null && employeeShareMarValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareMar = ((double)employeeShareMarValue);
                }
                JToken employeeShareMayValue = inputObject["EmployeeShareMay"];
                if (employeeShareMayValue != null && employeeShareMayValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareMay = ((double)employeeShareMayValue);
                }
                JToken employeeShareNovValue = inputObject["EmployeeShareNov"];
                if (employeeShareNovValue != null && employeeShareNovValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareNov = ((double)employeeShareNovValue);
                }
                JToken employeeShareOctValue = inputObject["EmployeeShareOct"];
                if (employeeShareOctValue != null && employeeShareOctValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareOct = ((double)employeeShareOctValue);
                }
                JToken employeeShareSepValue = inputObject["EmployeeShareSep"];
                if (employeeShareSepValue != null && employeeShareSepValue.Type != JTokenType.Null)
                {
                    this.EmployeeShareSep = ((double)employeeShareSepValue);
                }
                JToken employerPhoneValue = inputObject["EmployerPhone"];
                if (employerPhoneValue != null && employerPhoneValue.Type != JTokenType.Null)
                {
                    this.EmployerPhone = ((string)employerPhoneValue);
                }
                JToken filingIdValue = inputObject["FilingId"];
                if (filingIdValue != null && filingIdValue.Type != JTokenType.Null)
                {
                    this.FilingId = ((int)filingIdValue);
                }
                JToken firstNameValue = inputObject["FirstName"];
                if (firstNameValue != null && firstNameValue.Type != JTokenType.Null)
                {
                    this.FirstName = ((string)firstNameValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken isCorrectedValue = inputObject["IsCorrected"];
                if (isCorrectedValue != null && isCorrectedValue.Type != JTokenType.Null)
                {
                    this.IsCorrected = ((bool)isCorrectedValue);
                }
                JToken isSelfInsuredValue = inputObject["IsSelfInsured"];
                if (isSelfInsuredValue != null && isSelfInsuredValue.Type != JTokenType.Null)
                {
                    this.IsSelfInsured = ((bool)isSelfInsuredValue);
                }
                JToken lastNameValue = inputObject["LastName"];
                if (lastNameValue != null && lastNameValue.Type != JTokenType.Null)
                {
                    this.LastName = ((string)lastNameValue);
                }
                JToken middleNameValue = inputObject["MiddleName"];
                if (middleNameValue != null && middleNameValue.Type != JTokenType.Null)
                {
                    this.MiddleName = ((string)middleNameValue);
                }
                JToken numberOfCoveredIndividualsValue = inputObject["NumberOfCoveredIndividuals"];
                if (numberOfCoveredIndividualsValue != null && numberOfCoveredIndividualsValue.Type != JTokenType.Null)
                {
                    this.NumberOfCoveredIndividuals = ((int)numberOfCoveredIndividualsValue);
                }
                JToken offerOfCoverageAll12MonthsValue = inputObject["OfferOfCoverageAll12Months"];
                if (offerOfCoverageAll12MonthsValue != null && offerOfCoverageAll12MonthsValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageAll12Months = ((string)offerOfCoverageAll12MonthsValue);
                }
                JToken offerOfCoverageAprValue = inputObject["OfferOfCoverageApr"];
                if (offerOfCoverageAprValue != null && offerOfCoverageAprValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageApr = ((string)offerOfCoverageAprValue);
                }
                JToken offerOfCoverageAugValue = inputObject["OfferOfCoverageAug"];
                if (offerOfCoverageAugValue != null && offerOfCoverageAugValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageAug = ((string)offerOfCoverageAugValue);
                }
                JToken offerOfCoverageDecValue = inputObject["OfferOfCoverageDec"];
                if (offerOfCoverageDecValue != null && offerOfCoverageDecValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageDec = ((string)offerOfCoverageDecValue);
                }
                JToken offerOfCoverageFebValue = inputObject["OfferOfCoverageFeb"];
                if (offerOfCoverageFebValue != null && offerOfCoverageFebValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageFeb = ((string)offerOfCoverageFebValue);
                }
                JToken offerOfCoverageJanValue = inputObject["OfferOfCoverageJan"];
                if (offerOfCoverageJanValue != null && offerOfCoverageJanValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageJan = ((string)offerOfCoverageJanValue);
                }
                JToken offerOfCoverageJulValue = inputObject["OfferOfCoverageJul"];
                if (offerOfCoverageJulValue != null && offerOfCoverageJulValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageJul = ((string)offerOfCoverageJulValue);
                }
                JToken offerOfCoverageJunValue = inputObject["OfferOfCoverageJun"];
                if (offerOfCoverageJunValue != null && offerOfCoverageJunValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageJun = ((string)offerOfCoverageJunValue);
                }
                JToken offerOfCoverageMarValue = inputObject["OfferOfCoverageMar"];
                if (offerOfCoverageMarValue != null && offerOfCoverageMarValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageMar = ((string)offerOfCoverageMarValue);
                }
                JToken offerOfCoverageMayValue = inputObject["OfferOfCoverageMay"];
                if (offerOfCoverageMayValue != null && offerOfCoverageMayValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageMay = ((string)offerOfCoverageMayValue);
                }
                JToken offerOfCoverageNovValue = inputObject["OfferOfCoverageNov"];
                if (offerOfCoverageNovValue != null && offerOfCoverageNovValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageNov = ((string)offerOfCoverageNovValue);
                }
                JToken offerOfCoverageOctValue = inputObject["OfferOfCoverageOct"];
                if (offerOfCoverageOctValue != null && offerOfCoverageOctValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageOct = ((string)offerOfCoverageOctValue);
                }
                JToken offerOfCoverageSepValue = inputObject["OfferOfCoverageSep"];
                if (offerOfCoverageSepValue != null && offerOfCoverageSepValue.Type != JTokenType.Null)
                {
                    this.OfferOfCoverageSep = ((string)offerOfCoverageSepValue);
                }
                JToken planStartMonthValue = inputObject["PlanStartMonth"];
                if (planStartMonthValue != null && planStartMonthValue.Type != JTokenType.Null)
                {
                    this.PlanStartMonth = ((string)planStartMonthValue);
                }
                JToken ssnValue = inputObject["Ssn"];
                if (ssnValue != null && ssnValue.Type != JTokenType.Null)
                {
                    this.Ssn = ((string)ssnValue);
                }
                JToken stateValue = inputObject["State"];
                if (stateValue != null && stateValue.Type != JTokenType.Null)
                {
                    this.State = ((string)stateValue);
                }
                JToken statusValue = inputObject["Status"];
                if (statusValue != null && statusValue.Type != JTokenType.Null)
                {
                    this.Status = ((string)statusValue);
                }
                JToken suffixValue = inputObject["Suffix"];
                if (suffixValue != null && suffixValue.Type != JTokenType.Null)
                {
                    this.Suffix = ((string)suffixValue);
                }
                JToken zipValue = inputObject["Zip"];
                if (zipValue != null && zipValue.Type != JTokenType.Null)
                {
                    this.Zip = ((string)zipValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Form1095C
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Address == null)
            {
                throw new ArgumentNullException("Address");
            }
            if (this.City == null)
            {
                throw new ArgumentNullException("City");
            }
            if (this.EmployerPhone == null)
            {
                throw new ArgumentNullException("EmployerPhone");
            }
            if (this.FirstName == null)
            {
                throw new ArgumentNullException("FirstName");
            }
            if (this.LastName == null)
            {
                throw new ArgumentNullException("LastName");
            }
            if (this.Ssn == null)
            {
                throw new ArgumentNullException("Ssn");
            }
            if (this.State == null)
            {
                throw new ArgumentNullException("State");
            }
            if (this.Zip == null)
            {
                throw new ArgumentNullException("Zip");
            }
            if (this.Address != null)
            {
                outputObject["Address"] = this.Address;
            }
            if (this.Address2 != null)
            {
                outputObject["Address2"] = this.Address2;
            }
            if (this.ApplicableSection4980HAll12Months != null)
            {
                outputObject["ApplicableSection4980HAll12Months"] = this.ApplicableSection4980HAll12Months;
            }
            if (this.ApplicableSection4980HApr != null)
            {
                outputObject["ApplicableSection4980HApr"] = this.ApplicableSection4980HApr;
            }
            if (this.ApplicableSection4980HAug != null)
            {
                outputObject["ApplicableSection4980HAug"] = this.ApplicableSection4980HAug;
            }
            if (this.ApplicableSection4980HDec != null)
            {
                outputObject["ApplicableSection4980HDec"] = this.ApplicableSection4980HDec;
            }
            if (this.ApplicableSection4980HFeb != null)
            {
                outputObject["ApplicableSection4980HFeb"] = this.ApplicableSection4980HFeb;
            }
            if (this.ApplicableSection4980HJan != null)
            {
                outputObject["ApplicableSection4980HJan"] = this.ApplicableSection4980HJan;
            }
            if (this.ApplicableSection4980HJul != null)
            {
                outputObject["ApplicableSection4980HJul"] = this.ApplicableSection4980HJul;
            }
            if (this.ApplicableSection4980HJun != null)
            {
                outputObject["ApplicableSection4980HJun"] = this.ApplicableSection4980HJun;
            }
            if (this.ApplicableSection4980HMar != null)
            {
                outputObject["ApplicableSection4980HMar"] = this.ApplicableSection4980HMar;
            }
            if (this.ApplicableSection4980HMay != null)
            {
                outputObject["ApplicableSection4980HMay"] = this.ApplicableSection4980HMay;
            }
            if (this.ApplicableSection4980HNov != null)
            {
                outputObject["ApplicableSection4980HNov"] = this.ApplicableSection4980HNov;
            }
            if (this.ApplicableSection4980HOct != null)
            {
                outputObject["ApplicableSection4980HOct"] = this.ApplicableSection4980HOct;
            }
            if (this.ApplicableSection4980HSep != null)
            {
                outputObject["ApplicableSection4980HSep"] = this.ApplicableSection4980HSep;
            }
            if (this.City != null)
            {
                outputObject["City"] = this.City;
            }
            if (this.CountryCode != null)
            {
                outputObject["CountryCode"] = this.CountryCode;
            }
            JArray coveredIndividualsSequence = null;
            if (this.CoveredIndividuals != null)
            {
                if (this.CoveredIndividuals is ILazyCollection<CoveredIndividual> == false || ((ILazyCollection<CoveredIndividual>)this.CoveredIndividuals).IsInitialized)
                {
                    coveredIndividualsSequence = new JArray();
                    outputObject["CoveredIndividuals"] = coveredIndividualsSequence;
                    foreach (CoveredIndividual coveredIndividualsItem in this.CoveredIndividuals)
                    {
                        if (coveredIndividualsItem != null)
                        {
                            coveredIndividualsSequence.Add(coveredIndividualsItem.SerializeJson(null));
                        }
                    }
                }
            }
            if (this.DateEdited != null)
            {
                outputObject["DateEdited"] = this.DateEdited.Value;
            }
            if (this.EmployeeShareAll12Months != null)
            {
                outputObject["EmployeeShareAll12Months"] = this.EmployeeShareAll12Months.Value;
            }
            if (this.EmployeeShareApr != null)
            {
                outputObject["EmployeeShareApr"] = this.EmployeeShareApr.Value;
            }
            if (this.EmployeeShareAug != null)
            {
                outputObject["EmployeeShareAug"] = this.EmployeeShareAug.Value;
            }
            if (this.EmployeeShareDec != null)
            {
                outputObject["EmployeeShareDec"] = this.EmployeeShareDec.Value;
            }
            if (this.EmployeeShareFeb != null)
            {
                outputObject["EmployeeShareFeb"] = this.EmployeeShareFeb.Value;
            }
            if (this.EmployeeShareJan != null)
            {
                outputObject["EmployeeShareJan"] = this.EmployeeShareJan.Value;
            }
            if (this.EmployeeShareJul != null)
            {
                outputObject["EmployeeShareJul"] = this.EmployeeShareJul.Value;
            }
            if (this.EmployeeShareJun != null)
            {
                outputObject["EmployeeShareJun"] = this.EmployeeShareJun.Value;
            }
            if (this.EmployeeShareMar != null)
            {
                outputObject["EmployeeShareMar"] = this.EmployeeShareMar.Value;
            }
            if (this.EmployeeShareMay != null)
            {
                outputObject["EmployeeShareMay"] = this.EmployeeShareMay.Value;
            }
            if (this.EmployeeShareNov != null)
            {
                outputObject["EmployeeShareNov"] = this.EmployeeShareNov.Value;
            }
            if (this.EmployeeShareOct != null)
            {
                outputObject["EmployeeShareOct"] = this.EmployeeShareOct.Value;
            }
            if (this.EmployeeShareSep != null)
            {
                outputObject["EmployeeShareSep"] = this.EmployeeShareSep.Value;
            }
            if (this.EmployerPhone != null)
            {
                outputObject["EmployerPhone"] = this.EmployerPhone;
            }
            if (this.FilingId != null)
            {
                outputObject["FilingId"] = this.FilingId.Value;
            }
            if (this.FirstName != null)
            {
                outputObject["FirstName"] = this.FirstName;
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id.Value;
            }
            if (this.IsCorrected != null)
            {
                outputObject["IsCorrected"] = this.IsCorrected.Value;
            }
            if (this.IsSelfInsured != null)
            {
                outputObject["IsSelfInsured"] = this.IsSelfInsured.Value;
            }
            if (this.LastName != null)
            {
                outputObject["LastName"] = this.LastName;
            }
            if (this.MiddleName != null)
            {
                outputObject["MiddleName"] = this.MiddleName;
            }
            if (this.NumberOfCoveredIndividuals != null)
            {
                outputObject["NumberOfCoveredIndividuals"] = this.NumberOfCoveredIndividuals.Value;
            }
            if (this.OfferOfCoverageAll12Months != null)
            {
                outputObject["OfferOfCoverageAll12Months"] = this.OfferOfCoverageAll12Months;
            }
            if (this.OfferOfCoverageApr != null)
            {
                outputObject["OfferOfCoverageApr"] = this.OfferOfCoverageApr;
            }
            if (this.OfferOfCoverageAug != null)
            {
                outputObject["OfferOfCoverageAug"] = this.OfferOfCoverageAug;
            }
            if (this.OfferOfCoverageDec != null)
            {
                outputObject["OfferOfCoverageDec"] = this.OfferOfCoverageDec;
            }
            if (this.OfferOfCoverageFeb != null)
            {
                outputObject["OfferOfCoverageFeb"] = this.OfferOfCoverageFeb;
            }
            if (this.OfferOfCoverageJan != null)
            {
                outputObject["OfferOfCoverageJan"] = this.OfferOfCoverageJan;
            }
            if (this.OfferOfCoverageJul != null)
            {
                outputObject["OfferOfCoverageJul"] = this.OfferOfCoverageJul;
            }
            if (this.OfferOfCoverageJun != null)
            {
                outputObject["OfferOfCoverageJun"] = this.OfferOfCoverageJun;
            }
            if (this.OfferOfCoverageMar != null)
            {
                outputObject["OfferOfCoverageMar"] = this.OfferOfCoverageMar;
            }
            if (this.OfferOfCoverageMay != null)
            {
                outputObject["OfferOfCoverageMay"] = this.OfferOfCoverageMay;
            }
            if (this.OfferOfCoverageNov != null)
            {
                outputObject["OfferOfCoverageNov"] = this.OfferOfCoverageNov;
            }
            if (this.OfferOfCoverageOct != null)
            {
                outputObject["OfferOfCoverageOct"] = this.OfferOfCoverageOct;
            }
            if (this.OfferOfCoverageSep != null)
            {
                outputObject["OfferOfCoverageSep"] = this.OfferOfCoverageSep;
            }
            if (this.PlanStartMonth != null)
            {
                outputObject["PlanStartMonth"] = this.PlanStartMonth;
            }
            if (this.Ssn != null)
            {
                outputObject["Ssn"] = this.Ssn;
            }
            if (this.State != null)
            {
                outputObject["State"] = this.State;
            }
            if (this.Status != null)
            {
                outputObject["Status"] = this.Status;
            }
            if (this.Suffix != null)
            {
                outputObject["Suffix"] = this.Suffix;
            }
            if (this.Zip != null)
            {
                outputObject["Zip"] = this.Zip;
            }
            return outputObject;
        }
    }
}
