// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace BoomTax.Api.SampleProject.Models
{
    public static partial class Int32Collection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<int> DeserializeJson(JToken inputObject)
        {
            IList<int> deserializedObject = new List<int>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                deserializedObject.Add(((int)iListValue));
            }
            return deserializedObject;
        }
    }
}
